### ISSUE TITLE
ratio calculation returns 0

### ISSUE THREAD

**Issue by wpyung** [Ericbla/check_jenkins#5]
Result is always OK
e.g
OK: jobs count: 44|jobs=44;; passed=43 failed=1;1;19 disabled=0 running=0

line 133

	my $failed_ratio = $failed_jobs * 100 / $arctive_jobs;

this calculation works correctly when changed as follows

	$failed_ratio = $failed_jobs * 100 / $arctive_jobs;

e.g.
WARNING: jobs count: 44 Failed jobs ratio: 2.27272727272727%|jobs=44;; passed=43 failed=1;1;19 disabled=0 running=0

**Comment by Ericbla** [comment]
Thanks for reporting this issue.
It is now fixed and provides the ratio as a (rounded) integer %.

B.R.
